### ISSUE TITLE
It's not possible to select the text of rules for copy & pasting.

### ISSUE THREAD

**Issue by peterwilsoncc** [SudokuPad/sudokupad-web-issues#37]
Reference puzzle: https://tinyurl.com/2pjx8st8
Browser: Firefox 111/macOS 12.6.3

It's not possible to select the text of the rules in either the pop-over or the list of rules above the number pad.

To reproduce:

1. Ensure pause on start is enabled
2. Visit the link above
3. Attempt to select the text of the rules in the popover, it's not possible
4. Start the puzzle
5. Make same attempt in the rules above the number pad.

Gif

![copy-paste](https://user-images.githubusercontent.com/519727/229325437-715ea2e8-ad08-46d5-af33-53f6c36c4d00.gif)

**Comment by ewenmcneill** [comment]
This issue appear to be fixed in recent versions of SudokuPad by providing a icon, visible by hovering over the rules above the number pad, which will copy the puzzle name/rules to the clipboard: hover mouse over the rules area when the puzzle window is selected, a "two squares" icon should appear in the top left corner of the rules box, click on that "two squares" icon, and the rules are copied to the clipboard, and can be pasted into something else.  (From memory this feature was added in May or June 2023.)

So this issue can possibly be closed now?

Ewen

**Comment by killroy42** [comment]
Implemented via copy button a mentioned by @ewenmcneill .
